/**
 * Save-as-test — export a request/response as a passing `bun test` file
 * (console §9.2 · §11).
 */

/** Input for generating a save-as-test file. */
export interface SaveAsTestInput {
  /** Flow id (`bookings.create`). */
  readonly flowId: string;
  /** Request body used for invoke. */
  readonly request: unknown;
  /** Actual response body (assertions filled from this). */
  readonly response: unknown;
  /** Optional identity id used for invoke-as. */
  readonly asUserId?: string;
  /** File basename without extension. */
  readonly basename?: string;
}

/**
 * Emit the contents of a `bun test` file that asserts the captured response.
 *
 * The generated test is self-contained: it does not hit the network. It
 * freezes the request/response pair so regressions surface immediately.
 *
 * @param input - Captured invoke
 */
export function emitSaveAsTest(input: SaveAsTestInput): string {
  const safeName = sanitizeIdent(input.flowId);
  const basename = input.basename ?? `${safeName}.test`;
  const requestLit = literal(input.request);
  const responseLit = literal(input.response);
  const asUser = input.asUserId
    ? `\n  asUserId: ${literal(input.asUserId)},`
    : "";

  return `/**
 * Generated by oke Console — save as test.
 * Flow: ${input.flowId}
 * Do not edit by hand unless you intend to change the contract snapshot.
 */
import { describe, expect, test } from "bun:test";

const captured = {
  flowId: ${literal(input.flowId)},
  request: ${requestLit},
  response: ${responseLit},${asUser}
} as const;

describe(${literal(`save-as-test: ${input.flowId}`)}, () => {
  test("request snapshot is stable", () => {
    expect(captured.request).toEqual(${requestLit});
  });

  test("response snapshot is stable", () => {
    expect(captured.response).toEqual(${responseLit});
  });

  test("flow id is ${input.flowId}", () => {
    expect(captured.flowId).toBe(${literal(input.flowId)});
  });
});

// basename: ${basename}.ts
`;
}

/**
 * Suggested relative path for the generated test.
 *
 * @param flowId - Flow id
 */
export function saveAsTestPath(flowId: string): string {
  return `tests/flows/${sanitizeIdent(flowId)}.test.ts`;
}

/**
 * Write the generated test to disk and return the absolute path.
 *
 * @param dir - Target directory
 * @param input - Capture
 */
export async function writeSaveAsTest(
  dir: string,
  input: SaveAsTestInput,
): Promise<{ readonly path: string; readonly contents: string }> {
  const contents = emitSaveAsTest(input);
  const path = `${dir.replace(/\/$/, "")}/${sanitizeIdent(input.flowId)}.test.ts`;
  await Bun.write(path, contents);
  return { path, contents };
}

function sanitizeIdent(flowId: string): string {
  return flowId.replace(/[^a-zA-Z0-9._-]+/g, "_");
}

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}
