/**
 * `oke client add <url>` — ambient client types for a separate frontend repo.
 *
 * Fetches `GET {url}/_oke/client.json` and writes a compiling `.d.ts` that
 * augments `okengine/client`'s {@link Register} interface.
 */

import type { ClientDescriptor, ClientFetch } from "../client/types.ts";

/** Options for {@link clientAdd}. */
export interface ClientAddOptions {
  /** App base URL (required unless `descriptor` is provided). */
  readonly url?: string;
  /** Output path (default: `oke-client.d.ts`). */
  readonly out?: string;
  /** Override fetch (tests). */
  readonly fetch?: ClientFetch;
  /** Inject a descriptor instead of fetching (tests). */
  readonly descriptor?: ClientDescriptor;
}

/** Result of a successful {@link clientAdd}. */
export interface ClientAddResult {
  /** Absolute or relative path written. */
  readonly out: string;
  /** Emitted TypeScript declaration source. */
  readonly source: string;
}

/**
 * Fetch (or accept) a client descriptor and write an ambient declaration.
 *
 * @param options - URL / out / test overrides
 */
export async function clientAdd(
  options: ClientAddOptions,
): Promise<ClientAddResult> {
  const out = options.out ?? "oke-client.d.ts";
  const descriptor =
    options.descriptor ?? (await fetchDescriptor(options.url, options.fetch));
  const source = emitAmbient(descriptor);
  await Bun.write(out, source);
  return { out, source };
}

/**
 * CLI entry: parse `oke client add <url> [--out path]`.
 *
 * @param args - Args after `client add`
 */
export async function clientAddCli(args: readonly string[]): Promise<number> {
  const url = args.find((a) => !a.startsWith("-"));
  if (!url) {
    console.error("Usage: oke client add <url> [--out oke-client.d.ts]");
    return 1;
  }
  let out = "oke-client.d.ts";
  const outIdx = args.indexOf("--out");
  if (outIdx !== -1) {
    const next = args[outIdx + 1];
    if (!next) {
      console.error("--out requires a path");
      return 1;
    }
    out = next;
  }

  try {
    const result = await clientAdd({ url, out });
    console.log(`Wrote ${result.out}`);
    return 0;
  } catch (err) {
    console.error(err instanceof Error ? err.message : String(err));
    return 1;
  }
}

/**
 * Emit a compiling ambient module augmentation from a descriptor.
 *
 * @param descriptor - Routes with TS type strings
 */
export function emitAmbient(descriptor: ClientDescriptor): string {
  const units = Object.entries(descriptor.routes);
  const body =
    units.length === 0
      ? "      // no HTTP flows"
      : units
          .map(([unit, flows]) => {
            const flowLines = Object.entries(flows)
              .map(([flow, c]) => {
                const errors = c.errors
                  ? Object.entries(c.errors)
                      .map(([code, ty]) => `            ${JSON.stringify(code)}: ${ty}`)
                      .join(";\n")
                  : "";
                const errorBlock = errors
                  ? `          errors: {\n${errors};\n          };`
                  : "          errors: {};";
                return [
                  `        ${JSON.stringify(flow)}: {`,
                  `          in: ${c.in ?? "unknown"};`,
                  `          out: ${c.out ?? "unknown"};`,
                  errorBlock,
                  c.method
                    ? `          method: ${JSON.stringify(c.method)};`
                    : undefined,
                  c.path
                    ? `          path: ${JSON.stringify(c.path)};`
                    : undefined,
                  `        }`,
                ]
                  .filter((line): line is string => line !== undefined)
                  .join("\n");
              })
              .join(";\n");
            return `      ${JSON.stringify(unit)}: {\n${flowLines};\n      }`;
          })
          .join(";\n");

  return `/* eslint-disable */
/**
 * Generated by \`oke client add\` — do not edit by hand.
 * Ambient types for \`createClient(url)\` without importing App.
 */
declare module "okengine/client" {
  interface Register {
    app: {
      $routes: {
${body}
      };
    };
  }
}

export {};
`;
}

async function fetchDescriptor(
  url: string | undefined,
  fetchFn: ClientFetch = globalThis.fetch.bind(globalThis),
): Promise<ClientDescriptor> {
  if (!url) {
    throw new Error("client add requires <url>");
  }
  const base = url.replace(/\/+$/, "");
  const res = await fetchFn(`${base}/_oke/client.json`);
  if (!res.ok) {
    throw new Error(
      `Failed to fetch ${base}/_oke/client.json (${res.status})`,
    );
  }
  const json: unknown = await res.json();
  if (
    json === null ||
    typeof json !== "object" ||
    !("routes" in json) ||
    typeof (json as ClientDescriptor).routes !== "object"
  ) {
    throw new Error("Invalid client descriptor: missing routes");
  }
  return json as ClientDescriptor;
}
