// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";

export const activity = pgTable("activity", {
  id: text("id").primaryKey().$defaultFn(id),
  parentKind: text("parent_kind").notNull(),
  parentId: text("parent_id").notNull(),
  actorEmail: text("actor_email"),
  kind: text("kind").notNull(),
  body: text("body").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
