// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { tasks } from "./tasks.ts";

export const comments = pgTable("comments", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  authorEmail: text("author_email"),
  body: text("body").notNull(),
  resolvedAt: timestamp("resolved_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
