// generated by oke — do not edit
import { pgTable, text } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { custom_fields } from "./custom_fields.ts";
import { tasks } from "./tasks.ts";

export const custom_field_values = pgTable("custom_field_values", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  fieldId: text("field_id").notNull().references(() => custom_fields.id, { onDelete: "cascade" }),
  value: text("value").notNull(),
});
