// generated by oke — do not edit
import { pgTable, text } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { projects } from "./projects.ts";

export const custom_fields = pgTable("custom_fields", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
});
