// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";

export const documents = pgTable("documents", {
  id: text("id").primaryKey().$defaultFn(id),
  title: text("title").notNull(),
  body: text("body").notNull(),
  parentKind: text("parent_kind").notNull(),
  parentId: text("parent_id").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
