// generated by oke — do not edit
import { pgTable, text, bigint } from "drizzle-orm/pg-core";
import { id } from "okengine/store";

export const file_objects = pgTable("file_objects", {
  id: text("id").primaryKey().$defaultFn(id),
  objectKey: text("object_key").notNull(),
  originalName: text("original_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  storeRef: text("store_ref").notNull(),
});
