// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { projects } from "./projects.ts";

export const forms = pgTable("forms", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  schemaJson: text("schema_json").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
