// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { forms } from "./forms.ts";
import { tasks } from "./tasks.ts";

export const form_submissions = pgTable("form_submissions", {
  id: text("id").primaryKey().$defaultFn(id),
  formId: text("form_id").notNull().references(() => forms.id, { onDelete: "cascade" }),
  taskId: text("task_id").references(() => tasks.id, { onDelete: "set null" }),
  payloadJson: text("payload_json").notNull(),
  customerName: text("customer_name").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
