// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";

export const goals = pgTable("goals", {
  id: text("id").primaryKey().$defaultFn(id),
  name: text("name").notNull(),
  status: text("status").notNull(),
  ownerEmail: text("owner_email"),
  targetDate: timestamp("target_date", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
