// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";

export const inbox = pgTable("inbox", {
  id: text("id").primaryKey().$defaultFn(id),
  memberEmail: text("member_email").notNull(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  refId: text("ref_id").notNull(),
  readAt: timestamp("read_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
