// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { spaces } from "./spaces.ts";

export const members = pgTable("members", {
  id: text("id").primaryKey().$defaultFn(id),
  spaceId: text("space_id").references(() => spaces.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
