// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { goals } from "./goals.ts";
import { spaces } from "./spaces.ts";

export const projects = pgTable("projects", {
  id: text("id").primaryKey().$defaultFn(id),
  spaceId: text("space_id").notNull().references(() => spaces.id),
  goalId: text("goal_id").references(() => goals.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  status: text("status").notNull(),
  leadEmail: text("lead_email"),
  startDate: timestamp("start_date", { mode: "date" }),
  targetDate: timestamp("target_date", { mode: "date" }),
  color: text("color"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
