// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { projects } from "./projects.ts";

export const project_updates = pgTable("project_updates", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  health: text("health").notNull(),
  body: text("body").notNull(),
  authorEmail: text("author_email"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
