// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { tasks } from "./tasks.ts";

export const recurrence = pgTable("recurrence", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  every: text("every").notNull(),
  nextAt: timestamp("next_at", { mode: "date" }).notNull(),
});
