// generated by oke — do not edit
import { pgTable, text, bigint } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { projects } from "./projects.ts";

export const sections = pgTable("sections", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  sortOrder: bigint("sort_order", { mode: "number" }).notNull(),
});
