// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";

export const spaces = pgTable("spaces", {
  id: text("id").primaryKey().$defaultFn(id),
  key: text("key").notNull().unique(),
  name: text("name").notNull(),
  color: text("color"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
