// generated by oke — do not edit
import { pgTable, text } from "drizzle-orm/pg-core";
import { id } from "okengine/store";

export const tags = pgTable("tags", {
  id: text("id").primaryKey().$defaultFn(id),
  name: text("name").notNull(),
  groupName: text("group_name"),
});
