// generated by oke — do not edit
import { pgTable, text } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { tasks } from "./tasks.ts";

export const task_assignees = pgTable("task_assignees", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  assigneeEmail: text("assignee_email").notNull(),
});
