// generated by oke — do not edit
import { pgTable, text } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { tags } from "./tags.ts";
import { tasks } from "./tasks.ts";

export const task_tags = pgTable("task_tags", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id").notNull().references(() => tasks.id, { onDelete: "cascade" }),
  tagId: text("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
});
