// generated by oke — do not edit
import { pgTable, text, bigint, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { projects } from "./projects.ts";
import { sections } from "./sections.ts";
import { spaces } from "./spaces.ts";

export const tasks = pgTable("tasks", {
  id: text("id").primaryKey().$defaultFn(id),
  identifier: text("identifier").notNull().unique(),
  title: text("title").notNull(),
  description: text("description"),
  kind: text("kind").notNull(),
  priority: bigint("priority", { mode: "number" }).notNull(),
  estimate: bigint("estimate", { mode: "number" }),
  status: text("status").notNull(),
  spaceId: text("space_id").notNull().references(() => spaces.id),
  projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
  sectionId: text("section_id").references(() => sections.id, { onDelete: "set null" }),
  parentId: text("parent_id"),
  startDate: timestamp("start_date", { mode: "date" }),
  dueDate: timestamp("due_date", { mode: "date" }),
  completedAt: timestamp("completed_at", { mode: "date" }),
  archivedAt: timestamp("archived_at", { mode: "date" }),
  creatorEmail: text("creator_email"),
  roleNeeded: text("role_needed"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
  updatedAt: timestamp("updated_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
