// generated by oke — do not edit
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { id, nowDate } from "okengine/store";
import { projects } from "./projects.ts";

export const views = pgTable("views", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull().references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  kind: text("kind").notNull(),
  filtersJson: text("filters_json"),
  ownerEmail: text("owner_email"),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
});
