/**
 * `.adopt()` route-barrel generator — the disk-file alternative to a
 * virtual-module Bun plugin (investigated and rejected: `Bun.plugin()`'s
 * `onResolve` is never invoked for an unresolvable specifier during a plain
 * runtime `import()`, so `oke dev` and `oke build` would resolve a virtual
 * module differently — measured, not assumed).
 *
 * A real file on disk is an ordinary import: identical resolution under
 * `oke dev`'s runtime `import()` and `oke build`'s `Bun.build()`. Convention
 * (validated against every current example app — both `create-oke`
 * templates and the `skyport` compiler fixture, 7/7): every unit under
 * `<rootDir>/src/flows/*` has an `index.ts` barrel.
 */

import { readdir } from "node:fs/promises";
import { join } from "node:path";

/** Options for {@link generateAdoptBarrel}. */
export interface GenerateAdoptBarrelOptions {
  /** Project root (contains `src/flows`). */
  readonly rootDir: string;
  /** Flows directory relative to {@link rootDir} (default `"src/flows"`). */
  readonly flowsDir?: string;
}

/** Generated barrel source plus the unit names it covers. */
export interface AdoptBarrelResult {
  /** Full `.ts` source — write verbatim to the generated file. */
  readonly source: string;
  /** Unit (folder) names included, sorted. */
  readonly units: readonly string[];
  /** Folders under `flowsDir` skipped for lacking an `index.ts` barrel. */
  readonly skipped: readonly string[];
}

const GENERATED_HEADER =
  "// AUTO-GENERATED by `oke dev` / `oke build` — do not edit by hand.\n" +
  "// Regenerated from every `src/flows/<unit>/index.ts` unit folder.\n";

/** A folder name usable as an `export * as <name>` binding. */
const VALID_UNIT_NAME = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Scan `<rootDir>/<flowsDir>/*` and emit a barrel re-exporting every unit
 * folder's `index.ts` under its folder name — the same shape
 * `.adopt({ main, notes })` already takes by hand.
 *
 * Never throws: a missing/unreadable flows directory yields an empty
 * barrel, same posture as the rest of the lazy AoT tooling (best-effort,
 * boot-time checks are what enforce staleness — see
 * `assertAdoptBarrelFresh` in `kernel/boot.ts`).
 *
 * @param options - Root dir / flows dir override
 */
export async function generateAdoptBarrel(
  options: GenerateAdoptBarrelOptions,
): Promise<AdoptBarrelResult> {
  const flowsDir = options.flowsDir ?? "src/flows";
  const abs = join(options.rootDir, flowsDir);

  const units: string[] = [];
  const skipped: string[] = [];
  try {
    const dirents = await readdir(abs, { withFileTypes: true });
    for (const d of dirents.sort((a, b) => a.name.localeCompare(b.name))) {
      if (!d.isDirectory()) continue;
      const hasBarrel = await Bun.file(join(abs, d.name, "index.ts")).exists();
      if (!hasBarrel) {
        skipped.push(d.name);
        continue;
      }
      if (!VALID_UNIT_NAME.test(d.name)) {
        skipped.push(d.name);
        continue;
      }
      units.push(d.name);
    }
  } catch {
    // Missing flows dir — empty barrel, not a throw (mirrors extractManifest).
  }

  const lines = units.map((u) => `export * as ${u} from "./${u}/index.ts";`);
  const source = lines.length > 0 ? `${GENERATED_HEADER}${lines.join("\n")}\n` : GENERATED_HEADER;
  return { source, units, skipped };
}
