// generated by oke — do not edit
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { defineRelations } from "drizzle-orm";

export const links = sqliteTable("links", {
  id: text("id").primaryKey(),
  code: text("code").notNull().unique(),
  url: text("url").notNull(),
  userId: text("user_id").notNull(),
  clicks: integer("clicks").notNull().default(0),
  createdAt: integer("created_at").notNull(),
});

export const daily = sqliteTable("daily", {
  id: text("id").primaryKey(),
  code: text("code")
    .notNull()
    .references(() => links.code),
  day: text("day").notNull(),
  clicks: integer("clicks").notNull().default(0),
});

export const relations = defineRelations({ links, daily }, (r) => ({
  links: {
    daily: r.many.daily({ from: r.links.code, to: r.daily.code }),
  },
  daily: {
    link: r.one.links({ from: r.daily.code, to: r.links.code, optional: false }),
  },
}));
