/**
 * Fixture signals for unit tests and the axe gate.
 */

import type { SignalRecord } from "./types.ts";

/** Skyport-shaped Signals fixture covering once / broadcast / live + DLQ. */
export const SIGNALS_FIXTURE: readonly SignalRecord[] = [
  {
    name: "order-placed",
    delivery: "once",
    retries: 5,
    deadLetterEnabled: true,
    orphaned: false,
    pending: 12,
    inflight: 2,
    dead: 2,
    delivered: 480,
    outboxLagMs: 340,
    connections: 0,
    throughputPerSec: 4,
    schema: {
      type: "object",
      required: ["orderId", "amount"],
      properties: {
        orderId: { type: "string" },
        amount: { type: "number" },
        currency: { type: "string", enum: ["USD", "EUR"] },
      },
    },
    subscribers: [],
    recentLive: [],
    deadLetters: [
      {
        id: "dlq-1",
        signal: "order-placed",
        payload: { orderId: "ord_1", amount: 49.5, currency: "USD" },
        delivery: "once",
        attempts: 5,
        failures: [
          {
            code: "PaymentDeclined",
            message: "card declined",
            at: 1_700_000_001_000,
            attempt: 1,
          },
          {
            code: "PaymentDeclined",
            message: "card declined",
            at: 1_700_000_002_000,
            attempt: 2,
          },
          {
            code: "PaymentDeclined",
            message: "card declined",
            at: 1_700_000_003_000,
            attempt: 3,
          },
          {
            code: "PaymentDeclined",
            message: "card declined",
            at: 1_700_000_004_000,
            attempt: 4,
          },
          {
            code: "GatewayTimeout",
            message: "upstream timed out",
            at: 1_700_000_005_000,
            attempt: 5,
          },
        ],
        createdAt: 1_700_000_000_000,
        availableAt: 1_700_000_005_000,
        status: "dead",
        causeRunId: "run-create-ok",
        causeFlow: "bookings.create",
      },
      {
        id: "dlq-2",
        signal: "order-placed",
        payload: { orderId: "ord_2", amount: 12, currency: "EUR" },
        delivery: "once",
        attempts: 5,
        failures: [
          {
            code: "GatewayTimeout",
            message: "upstream timed out",
            at: 1_700_000_010_000,
            attempt: 5,
          },
        ],
        createdAt: 1_700_000_009_000,
        availableAt: 1_700_000_010_000,
        status: "dead",
        causeRunId: "run-create-fail",
        causeFlow: "bookings.create",
      },
    ],
    producers: [
      {
        flowId: "bookings.create",
        durable: false,
        external: false,
        peakTier: "emits",
      },
    ],
    consumers: [
      {
        flowId: "fulfillment.onOrder",
        durable: false,
        external: true,
        peakTier: "external",
      },
      {
        flowId: "payments.chargeBooking",
        durable: true,
        external: false,
        peakTier: "capabilities",
      },
    ],
    consumersDurable: false,
  },
  {
    name: "inventory-changed",
    delivery: "broadcast",
    retries: 3,
    deadLetterEnabled: true,
    orphaned: false,
    pending: 3,
    inflight: 0,
    dead: 0,
    delivered: 90,
    outboxLagMs: 12,
    connections: 0,
    throughputPerSec: 1,
    schema: {
      type: "object",
      properties: { sku: { type: "string" }, delta: { type: "integer" } },
    },
    subscribers: [
      { id: "cache-warmer", lag: 2, errorCount: 0 },
      { id: "search-indexer", lag: 1, errorCount: 3 },
    ],
    recentLive: [],
    deadLetters: [],
    producers: [
      {
        flowId: "inventory.adjust",
        durable: false,
        external: false,
        peakTier: "emits",
      },
    ],
    consumers: [
      {
        flowId: "cache.onInventory",
        durable: true,
        external: false,
        peakTier: "writes",
      },
      {
        flowId: "search.onInventory",
        durable: true,
        external: false,
        peakTier: "writes",
      },
    ],
    consumersDurable: true,
  },
  {
    name: "ops-feed",
    delivery: "live",
    retries: 0,
    deadLetterEnabled: false,
    orphaned: false,
    pending: 0,
    inflight: 0,
    dead: 0,
    delivered: 1_204,
    outboxLagMs: null,
    connections: 7,
    throughputPerSec: 18,
    schema: undefined,
    subscribers: [],
    recentLive: [
      { kind: "heartbeat", at: 1 },
      { kind: "alert", code: "lag", at: 2 },
      { kind: "heartbeat", at: 3 },
    ],
    deadLetters: [],
    producers: [
      {
        flowId: "ops.emit",
        durable: false,
        external: false,
        peakTier: "emits",
      },
    ],
    consumers: [],
    consumersDurable: null,
  },
  {
    name: "legacy-shipped",
    delivery: "once",
    retries: 3,
    deadLetterEnabled: true,
    orphaned: true,
    pending: 4,
    inflight: 0,
    dead: 1,
    delivered: 0,
    outboxLagMs: 86_400_000,
    connections: 0,
    throughputPerSec: 0,
    schema: undefined,
    subscribers: [],
    recentLive: [],
    deadLetters: [
      {
        id: "dlq-orphan",
        signal: "legacy-shipped",
        payload: { shipmentId: "shp_9" },
        delivery: "once",
        attempts: 3,
        failures: [
          {
            code: "NoConsumer",
            message: "signal removed from code",
            at: 1_700_000_100_000,
            attempt: 3,
          },
        ],
        createdAt: 1_700_000_090_000,
        availableAt: 1_700_000_100_000,
        status: "dead",
      },
    ],
    producers: [],
    consumers: [],
    consumersDurable: null,
  },
];
