// AUTO-GENERATED by `oke dev` / `oke build` — do not edit by hand.
// Regenerated from every `src/flows/<unit>/` folder (barrel or file tree).
import { registerFlowUnits } from "okengine";
import * as attachments from "./attachments/index.ts";
export { attachments };

import * as comments from "./comments/index.ts";
export { comments };

import * as digest from "./digest/index.ts";
export { digest };

import * as documents from "./documents/index.ts";
export { documents };

import * as drafts from "./drafts/index.ts";
export { drafts };

import * as forms from "./forms/index.ts";
export { forms };

import * as github from "./github/index.ts";
export { github };

import * as goals from "./goals/index.ts";
export { goals };

import * as inbox from "./inbox/index.ts";
export { inbox };

import * as main from "./main/index.ts";
export { main };

import * as members from "./members/index.ts";
export { members };

import * as my from "./my/index.ts";
export { my };

import * as notify from "./notify/index.ts";
export { notify };

import * as overdue from "./overdue/index.ts";
export { overdue };

import * as projects from "./projects/index.ts";
export { projects };

import * as recurring from "./recurring/index.ts";
export { recurring };

import * as search from "./search/index.ts";
export { search };

import * as slack from "./slack/index.ts";
export { slack };

import * as spaces from "./spaces/index.ts";
export { spaces };

import * as tags from "./tags/index.ts";
export { tags };

import * as tasks from "./tasks/index.ts";
export { tasks };

import * as views from "./views/index.ts";
export { views };

import * as webhooks from "./webhooks/index.ts";
export { webhooks };
registerFlowUnits({
  attachments,
  comments,
  digest,
  documents,
  drafts,
  forms,
  github,
  goals,
  inbox,
  main,
  members,
  my,
  notify,
  overdue,
  projects,
  recurring,
  search,
  slack,
  spaces,
  tags,
  tasks,
  views,
  webhooks,
});
declare module "okengine" {
  interface RegisteredFlowUnits {
    readonly attachments: typeof attachments;
    readonly comments: typeof comments;
    readonly digest: typeof digest;
    readonly documents: typeof documents;
    readonly drafts: typeof drafts;
    readonly forms: typeof forms;
    readonly github: typeof github;
    readonly goals: typeof goals;
    readonly inbox: typeof inbox;
    readonly main: typeof main;
    readonly members: typeof members;
    readonly my: typeof my;
    readonly notify: typeof notify;
    readonly overdue: typeof overdue;
    readonly projects: typeof projects;
    readonly recurring: typeof recurring;
    readonly search: typeof search;
    readonly slack: typeof slack;
    readonly spaces: typeof spaces;
    readonly tags: typeof tags;
    readonly tasks: typeof tasks;
    readonly views: typeof views;
    readonly webhooks: typeof webhooks;
  }
}
