// generated by oke — do not edit
import { pgTable, text, bigint } from "drizzle-orm/pg-core";

import { id } from "okengine/store";

export const comments = pgTable("comments", {
  id: text("id").primaryKey().$defaultFn(id),
  issueId: text("issue_id").notNull(),
  authorEmail: text("author_email"),
  body: text("body").notNull(),
  resolvedAt: text("resolved_at"),
});

export const customer_requests = pgTable("customer_requests", {
  id: text("id").primaryKey().$defaultFn(id),
  issueId: text("issue_id").notNull(),
  customerName: text("customer_name").notNull(),
  body: text("body").notNull(),
});

export const cycles = pgTable("cycles", {
  id: text("id").primaryKey().$defaultFn(id),
  teamId: text("team_id").notNull(),
  number: bigint("number", { mode: "number" }).notNull(),
  name: text("name").notNull(),
  startsAt: text("starts_at").notNull(),
  endsAt: text("ends_at").notNull(),
  state: text("state").notNull(),
});

export const documents = pgTable("documents", {
  id: text("id").primaryKey().$defaultFn(id),
  title: text("title").notNull(),
  body: text("body").notNull(),
  parentKind: text("parent_kind").notNull(),
  parentId: text("parent_id").notNull(),
});

export const file_objects = pgTable("file_objects", {
  id: text("id").primaryKey().$defaultFn(id),
  objectKey: text("object_key").notNull(),
  originalName: text("original_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  storeRef: text("store_ref").notNull(),
});

export const initiatives = pgTable("initiatives", {
  id: text("id").primaryKey().$defaultFn(id),
  name: text("name").notNull(),
  status: text("status").notNull(),
  ownerEmail: text("owner_email"),
  targetDate: text("target_date"),
});

export const issue_labels = pgTable("issue_labels", {
  id: text("id").primaryKey().$defaultFn(id),
  issueId: text("issue_id").notNull(),
  labelId: text("label_id").notNull(),
});

export const issues = pgTable("issues", {
  id: text("id").primaryKey().$defaultFn(id),
  identifier: text("identifier").notNull(),
  title: text("title").notNull(),
  description: text("description"),
  priority: bigint("priority", { mode: "number" }).notNull(),
  estimate: bigint("estimate", { mode: "number" }),
  stateId: text("state_id").notNull(),
  teamId: text("team_id").notNull(),
  projectId: text("project_id"),
  milestoneId: text("milestone_id"),
  cycleId: text("cycle_id"),
  parentId: text("parent_id"),
  assigneeEmail: text("assignee_email"),
  creatorEmail: text("creator_email"),
  dueDate: text("due_date"),
  slaBreachesAt: text("sla_breaches_at"),
  triagedAt: text("triaged_at"),
  archivedAt: text("archived_at"),
});

export const labels = pgTable("labels", {
  id: text("id").primaryKey().$defaultFn(id),
  teamId: text("team_id"),
  name: text("name").notNull(),
  groupName: text("group_name"),
});

export const members = pgTable("members", {
  id: text("id").primaryKey().$defaultFn(id),
  teamId: text("team_id").notNull(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
});

export const project_milestones = pgTable("project_milestones", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull(),
  name: text("name").notNull(),
  targetDate: text("target_date"),
  sortOrder: bigint("sort_order", { mode: "number" }).notNull(),
});

export const project_updates = pgTable("project_updates", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id").notNull(),
  health: text("health").notNull(),
  body: text("body").notNull(),
  authorEmail: text("author_email"),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey().$defaultFn(id),
  initiativeId: text("initiative_id").notNull(),
  name: text("name").notNull(),
  status: text("status").notNull(),
  leadEmail: text("lead_email"),
  targetDate: text("target_date"),
  progress: bigint("progress", { mode: "number" }).notNull(),
});

export const teams = pgTable("teams", {
  id: text("id").primaryKey().$defaultFn(id),
  key: text("key").notNull(),
  name: text("name").notNull(),
  parentId: text("parent_id"),
});

export const workflow_states = pgTable("workflow_states", {
  id: text("id").primaryKey().$defaultFn(id),
  teamId: text("team_id").notNull(),
  name: text("name").notNull(),
  type: text("type").notNull(),
  position: bigint("position", { mode: "number" }).notNull(),
});
