// generated by oke — do not edit
import { pgTable, text, bigint } from "drizzle-orm/pg-core";
import { defineRelations } from "drizzle-orm";
import { id, now } from "okengine/store";

export const activity = pgTable("activity", {
  id: text("id").primaryKey().$defaultFn(id),
  parentKind: text("parent_kind").notNull(),
  parentId: text("parent_id").notNull(),
  actorEmail: text("actor_email"),
  kind: text("kind").notNull(),
  body: text("body").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const comments = pgTable("comments", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  authorEmail: text("author_email"),
  body: text("body").notNull(),
  resolvedAt: text("resolved_at"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const custom_field_values = pgTable("custom_field_values", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  fieldId: text("field_id")
    .notNull()
    .references(() => custom_fields.id, { onDelete: "cascade" }),
  value: text("value").notNull(),
});

export const custom_fields = pgTable("custom_fields", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  type: text("type").notNull(),
});

export const documents = pgTable("documents", {
  id: text("id").primaryKey().$defaultFn(id),
  title: text("title").notNull(),
  body: text("body").notNull(),
  parentKind: text("parent_kind").notNull(),
  parentId: text("parent_id").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const file_objects = pgTable("file_objects", {
  id: text("id").primaryKey().$defaultFn(id),
  objectKey: text("object_key").notNull(),
  originalName: text("original_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  storeRef: text("store_ref").notNull(),
});

export const form_submissions = pgTable("form_submissions", {
  id: text("id").primaryKey().$defaultFn(id),
  formId: text("form_id")
    .notNull()
    .references(() => forms.id, { onDelete: "cascade" }),
  taskId: text("task_id").references(() => tasks.id, { onDelete: "set null" }),
  payloadJson: text("payload_json").notNull(),
  customerName: text("customer_name").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const forms = pgTable("forms", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  schemaJson: text("schema_json").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const goals = pgTable("goals", {
  id: text("id").primaryKey().$defaultFn(id),
  name: text("name").notNull(),
  status: text("status").notNull(),
  ownerEmail: text("owner_email"),
  targetDate: text("target_date"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const inbox = pgTable("inbox", {
  id: text("id").primaryKey().$defaultFn(id),
  memberEmail: text("member_email").notNull(),
  kind: text("kind").notNull(),
  title: text("title").notNull(),
  refId: text("ref_id").notNull(),
  readAt: text("read_at"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const members = pgTable("members", {
  id: text("id").primaryKey().$defaultFn(id),
  spaceId: text("space_id").references(() => spaces.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  email: text("email").notNull(),
  role: text("role").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const project_updates = pgTable("project_updates", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  health: text("health").notNull(),
  body: text("body").notNull(),
  authorEmail: text("author_email"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const projects = pgTable("projects", {
  id: text("id").primaryKey().$defaultFn(id),
  spaceId: text("space_id")
    .notNull()
    .references(() => spaces.id),
  goalId: text("goal_id").references(() => goals.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  status: text("status").notNull(),
  leadEmail: text("lead_email"),
  startDate: text("start_date"),
  targetDate: text("target_date"),
  color: text("color"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const recurrence = pgTable("recurrence", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  every: text("every").notNull(),
  nextAt: text("next_at").notNull(),
});

export const sections = pgTable("sections", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  sortOrder: bigint("sort_order", { mode: "number" }).notNull(),
});

export const spaces = pgTable("spaces", {
  id: text("id").primaryKey().$defaultFn(id),
  key: text("key").notNull().unique(),
  name: text("name").notNull(),
  color: text("color"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const tags = pgTable("tags", {
  id: text("id").primaryKey().$defaultFn(id),
  name: text("name").notNull(),
  groupName: text("group_name"),
});

export const task_assignees = pgTable("task_assignees", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  assigneeEmail: text("assignee_email").notNull(),
});

export const task_dependencies = pgTable("task_dependencies", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  blocksTaskId: text("blocks_task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
});

export const task_followers = pgTable("task_followers", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  followerEmail: text("follower_email").notNull(),
});

export const task_tags = pgTable("task_tags", {
  id: text("id").primaryKey().$defaultFn(id),
  taskId: text("task_id")
    .notNull()
    .references(() => tasks.id, { onDelete: "cascade" }),
  tagId: text("tag_id")
    .notNull()
    .references(() => tags.id, { onDelete: "cascade" }),
});

export const tasks = pgTable("tasks", {
  id: text("id").primaryKey().$defaultFn(id),
  identifier: text("identifier").notNull().unique(),
  title: text("title").notNull(),
  description: text("description"),
  kind: text("kind").notNull(),
  priority: bigint("priority", { mode: "number" }).notNull(),
  estimate: bigint("estimate", { mode: "number" }),
  status: text("status").notNull(),
  spaceId: text("space_id")
    .notNull()
    .references(() => spaces.id),
  projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
  sectionId: text("section_id").references(() => sections.id, { onDelete: "set null" }),
  parentId: text("parent_id"),
  startDate: text("start_date"),
  dueDate: text("due_date"),
  completedAt: text("completed_at"),
  archivedAt: text("archived_at"),
  creatorEmail: text("creator_email"),
  roleNeeded: text("role_needed"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const views = pgTable("views", {
  id: text("id").primaryKey().$defaultFn(id),
  projectId: text("project_id")
    .notNull()
    .references(() => projects.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  kind: text("kind").notNull(),
  filtersJson: text("filters_json"),
  ownerEmail: text("owner_email"),
  createdAt: bigint("created_at", { mode: "number" }).notNull().$defaultFn(now),
});

export const relations = defineRelations(
  {
    spaces,
    members,
    goals,
    projects,
    sections,
    tasks,
    task_assignees,
    task_followers,
    task_dependencies,
    tags,
    task_tags,
    custom_fields,
    custom_field_values,
    comments,
    activity,
    documents,
    file_objects,
    project_updates,
    views,
    forms,
    form_submissions,
    inbox,
    recurrence,
  },
  (r) => ({
    spaces: {
      members: r.many.members({ from: r.spaces.id, to: r.members.spaceId }),
      projects: r.many.projects({ from: r.spaces.id, to: r.projects.spaceId }),
    },
    members: {
      space: r.one.spaces({ from: r.members.spaceId, to: r.spaces.id }),
    },
    goals: {
      projects: r.many.projects({ from: r.goals.id, to: r.projects.goalId }),
    },
    projects: {
      space: r.one.spaces({ from: r.projects.spaceId, to: r.spaces.id, optional: false }),
      goal: r.one.goals({ from: r.projects.goalId, to: r.goals.id }),
      sections: r.many.sections({ from: r.projects.id, to: r.sections.projectId }),
      tasks: r.many.tasks({ from: r.projects.id, to: r.tasks.projectId }),
      updates: r.many.project_updates({ from: r.projects.id, to: r.project_updates.projectId }),
      views: r.many.views({ from: r.projects.id, to: r.views.projectId }),
      forms: r.many.forms({ from: r.projects.id, to: r.forms.projectId }),
    },
    sections: {
      project: r.one.projects({ from: r.sections.projectId, to: r.projects.id, optional: false }),
      tasks: r.many.tasks({ from: r.sections.id, to: r.tasks.sectionId }),
    },
    tasks: {
      space: r.one.spaces({ from: r.tasks.spaceId, to: r.spaces.id, optional: false }),
      project: r.one.projects({ from: r.tasks.projectId, to: r.projects.id }),
      section: r.one.sections({ from: r.tasks.sectionId, to: r.sections.id }),
      parent: r.one.tasks({ from: r.tasks.parentId, to: r.tasks.id }),
      assignees: r.many.task_assignees({ from: r.tasks.id, to: r.task_assignees.taskId }),
      followers: r.many.task_followers({ from: r.tasks.id, to: r.task_followers.taskId }),
      comments: r.many.comments({ from: r.tasks.id, to: r.comments.taskId }),
      tags: r.many.task_tags({ from: r.tasks.id, to: r.task_tags.taskId }),
    },
    task_assignees: {
      task: r.one.tasks({ from: r.task_assignees.taskId, to: r.tasks.id, optional: false }),
    },
    comments: {
      task: r.one.tasks({ from: r.comments.taskId, to: r.tasks.id, optional: false }),
    },
    forms: {
      project: r.one.projects({ from: r.forms.projectId, to: r.projects.id, optional: false }),
      submissions: r.many.form_submissions({ from: r.forms.id, to: r.form_submissions.formId }),
    },
    form_submissions: {
      form: r.one.forms({ from: r.form_submissions.formId, to: r.forms.id, optional: false }),
      task: r.one.tasks({ from: r.form_submissions.taskId, to: r.tasks.id }),
    },
  }),
);
