/* eslint-disable */
/**
 * Generated by `oke client add` — do not edit by hand.
 * Runtime route stamps for createClient(url, { $routes: routes }).
 */
export const routes = {
  "attachments": {
    "get": {
    method: "GET",
    path: "/attachments/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/tasks/:id/attachments",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/attachments/:id",
    gates: ["member","files:write"] as const,
  },
    "upload": {
    method: "POST",
    path: "/attachments",
    gates: ["member","task:write"] as const,
  },
  },
  "comments": {
    "create": {
    method: "POST",
    path: "/tasks/:id/comments",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/comments/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/tasks/:id/comments",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/comments/:id",
    gates: ["member","comment:write","rate:sliding-window-counter:120/1m"] as const,
  },
    "resolve": {
    method: "POST",
    path: "/comments/:id/resolve",
    gates: ["member","comment:write","rate:sliding-window-counter:120/1m"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/comments/:id",
    gates: ["member","comment:write","rate:sliding-window-counter:120/1m"] as const,
  },
  },
  "digest": {
    "daily": {},
  },
  "documents": {
    "get": {
    method: "GET",
    path: "/documents/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/documents",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/documents/:id",
    gates: ["member"] as const,
  },
    "summarize": {
    method: "POST",
    path: "/documents/:id/summarize",
    gates: ["member"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/documents/:id",
    gates: ["member"] as const,
  },
    "upsert": {
    method: "POST",
    path: "/documents",
    gates: ["member"] as const,
  },
  },
  "drafts": {
    "discard": {
    method: "DELETE",
    path: "/drafts/:id",
    gates: ["member"] as const,
  },
    "expire": {},
    "list": {
    method: "GET",
    path: "/drafts",
    gates: ["member"] as const,
  },
    "save": {
    method: "PUT",
    path: "/drafts/:id",
    gates: ["member"] as const,
  },
  },
  "forms": {
    "create": {
    method: "POST",
    path: "/forms",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/forms/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/forms",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/forms/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "submit": {
    method: "POST",
    path: "/forms/:id/submit",
    gates: ["member"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/forms/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "github": {
    "disconnect": {
    method: "DELETE",
    path: "/integrations/github",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "ingest": {
    method: "POST",
    path: "/integrations/github",
    gates: ["member"] as const,
  },
    "status": {
    method: "GET",
    path: "/integrations/github",
    gates: ["member"] as const,
  },
  },
  "goals": {
    "create": {
    method: "POST",
    path: "/goals",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/goals/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/goals",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/goals/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "rollup": {},
    "update": {
    method: "PATCH",
    path: "/goals/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "inbox": {
    "list": {
    method: "GET",
    path: "/inbox",
    gates: ["member"] as const,
  },
    "read": {
    method: "POST",
    path: "/inbox/:id/read",
    gates: ["member"] as const,
  },
  },
  "main": {
    "health": {
    method: "GET",
    path: "/health",
    gates: ["public"] as const,
  },
    "root": {
    method: "GET",
    path: "/",
    gates: ["public"] as const,
  },
  },
  "members": {
    "get": {
    method: "GET",
    path: "/members/:id",
    gates: ["member"] as const,
  },
    "invite": {
    method: "POST",
    path: "/members/invite",
    gates: ["member","member:admin"] as const,
  },
    "list": {
    method: "GET",
    path: "/members",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/members/:id",
    gates: ["member","member:admin"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/members/:id",
    gates: ["member","member:admin"] as const,
  },
  },
  "my": {
    "plan": {
    method: "POST",
    path: "/me/plan",
    gates: ["member"] as const,
  },
    "tasksMine": {
    method: "GET",
    path: "/me/tasks",
    gates: ["member"] as const,
  },
  },
  "notify": {
    "onComment": {},
    "onComplete": {},
    "onDraft": {},
    "onForm": {},
    "onGoal": {},
    "onGoalChanged": {},
    "onProject": {},
    "onTask": {},
  },
  "overdue": {
    "watch": {},
  },
  "projects": {
    "addSection": {
    method: "POST",
    path: "/projects/:id/sections",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "archive": {
    method: "POST",
    path: "/projects/:id/archive",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "create": {
    method: "POST",
    path: "/projects",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/projects/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/projects",
    gates: ["member"] as const,
  },
    "listSections": {
    method: "GET",
    path: "/projects/:id/sections",
    gates: ["member"] as const,
  },
    "listUpdates": {
    method: "GET",
    path: "/projects/:id/updates",
    gates: ["member"] as const,
  },
    "postUpdate": {
    method: "POST",
    path: "/projects/:id/updates",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/projects/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/projects/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "recurring": {
    "spawn": {},
  },
  "search": {
    "embedTask": {},
    "indexOnCreate": {},
    "onComment": {},
    "onComplete": {},
    "onForm": {},
    "onProject": {},
    "query": {
    method: "QUERY",
    path: "/search",
    gates: ["member"] as const,
  },
    "reindex": {
    method: "POST",
    path: "/search/reindex",
    gates: ["member"] as const,
  },
    "suggest": {
    method: "GET",
    path: "/search/suggest",
    gates: ["member"] as const,
  },
  },
  "slack": {
    "ingest": {
    method: "POST",
    path: "/integrations/slack",
    gates: ["member"] as const,
  },
  },
  "spaces": {
    "create": {
    method: "POST",
    path: "/spaces",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/spaces/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/spaces",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/spaces/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/spaces/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "tags": {
    "create": {
    method: "POST",
    path: "/tags",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/tags/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/tags",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/tags/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/tags/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "tasks": {
    "addTag": {
    method: "POST",
    path: "/tasks/:id/tags",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "archive": {
    method: "POST",
    path: "/tasks/:id/archive",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "assign": {
    method: "POST",
    path: "/tasks/:id/assign",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "complete": {
    method: "POST",
    path: "/tasks/:id/complete",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "create": {
    method: "POST",
    path: "/tasks",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "depend": {
    method: "POST",
    path: "/tasks/:id/depend",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "duplicate": {
    method: "POST",
    path: "/tasks/:id/duplicate",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "follow": {
    method: "POST",
    path: "/tasks/:id/follow",
    gates: ["member"] as const,
  },
    "get": {
    method: "GET",
    path: "/tasks/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/tasks",
    gates: ["member"] as const,
  },
    "live": {
    method: "GET",
    path: "/tasks/live",
    live: "tasks",
    stream: true as const,
    matchKey: [] as const,
    gates: ["member"] as const,
  },
    "move": {
    method: "POST",
    path: "/tasks/:id/move",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "onStatus": {},
    "remove": {
    method: "DELETE",
    path: "/tasks/:id",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
    "unfollow": {
    method: "POST",
    path: "/tasks/:id/unfollow",
    gates: ["member"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/tasks/:id",
    gates: ["member","task:write","rate:sliding-window-counter:60/1m"] as const,
  },
  },
  "views": {
    "board": {
    method: "GET",
    path: "/views/:id/board",
    gates: ["member"] as const,
  },
    "create": {
    method: "POST",
    path: "/views",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "get": {
    method: "GET",
    path: "/views/:id",
    gates: ["member"] as const,
  },
    "list": {
    method: "GET",
    path: "/views",
    gates: ["member"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/views/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
    "update": {
    method: "PATCH",
    path: "/views/:id",
    gates: ["member","project:admin","rate:token-bucket:40/1m"] as const,
  },
  },
  "webhooks": {
    "create": {
    method: "POST",
    path: "/webhooks",
    gates: ["member","webhook:admin"] as const,
  },
    "list": {
    method: "GET",
    path: "/webhooks",
    gates: ["member","webhook:admin"] as const,
  },
    "remove": {
    method: "DELETE",
    path: "/webhooks/:id",
    gates: ["member","webhook:admin"] as const,
  },
    "rotate": {
    method: "POST",
    path: "/webhooks/:id/rotate",
    gates: ["member","webhook:admin"] as const,
  },
  },
} as const;

export default routes;
