/* eslint-disable */
/**
 * Generated by `oke client add` — do not edit by hand.
 * Ambient types for `createClient(url)` without importing App.
 * Pair with `oke-client.routes.ts`: createClient(url, { $routes: routes }).
 */
declare module "okengine/client" {
  interface Register {
    app: {
      $routes: {
      "attachments": {
        "get": {
          in: { "id": string };
          out: { "id": string; "objectKey": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/attachments/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "id": string };
          out: readonly { "id": string; "objectKey": string }[];
          errors: {};
          method: "GET";
          path: "/tasks/:id/attachments";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/attachments/:id";
          gates: ["member","files:write"];
        };
        "upload": {
          in: { "taskId"?: string; "id"?: string; "name": string; "text": string; "contentType"?: string };
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/attachments";
          gates: ["member","task:write"];
        };
      };
      "comments": {
        "create": {
          in: { "id": string; "body": string };
          out: { "id": string; "taskId": string; "authorEmail": string | null; "body": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/comments";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "get": {
          in: { "id": string };
          out: { "id": string; "taskId": string; "authorEmail": string | null; "body": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/comments/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "id": string };
          out: readonly { "id": string; "taskId": string; "authorEmail": string | null; "body": string }[];
          errors: {};
          method: "GET";
          path: "/tasks/:id/comments";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/comments/:id";
          gates: ["member","comment:write","rate:sliding-window-counter:120/1m"];
        };
        "resolve": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
          method: "POST";
          path: "/comments/:id/resolve";
          gates: ["member","comment:write","rate:sliding-window-counter:120/1m"];
        };
        "update": {
          in: { "id": string; "body": string };
          out: { "id": string; "taskId": string; "authorEmail": string | null; "body": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/comments/:id";
          gates: ["member","comment:write","rate:sliding-window-counter:120/1m"];
        };
      };
      "digest": {
        "daily": {
          in: unknown;
          out: unknown;
          errors: {};
        };
      };
      "documents": {
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/documents/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/documents";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/documents/:id";
          gates: ["member"];
        };
        "summarize": {
          in: { "id": string };
          out: { "summary": string };
          errors: {
            "NotFound": { "id": string };
            "Unavailable": { "message": string };
          };
          method: "POST";
          path: "/documents/:id/summarize";
          gates: ["member"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/documents/:id";
          gates: ["member"];
        };
        "upsert": {
          in: { "title": string; "body": string; "parentKind": string; "parentId": string; "id"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/documents";
          gates: ["member"];
        };
      };
      "drafts": {
        "discard": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
          method: "DELETE";
          path: "/drafts/:id";
          gates: ["member"];
        };
        "expire": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly { "id": string; "title": string }[];
          errors: {};
          method: "GET";
          path: "/drafts";
          gates: ["member"];
        };
        "save": {
          in: { "id": string; "title": string; "body"?: string };
          out: { "id": string };
          errors: {};
          method: "PUT";
          path: "/drafts/:id";
          gates: ["member"];
        };
      };
      "forms": {
        "create": {
          in: { "projectId": string; "name": string; "schemaJson"?: string };
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/forms";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/forms/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/forms";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/forms/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "submit": {
          in: { "id": string; "title"?: string; "body"?: string; "customerName": string };
          out: { "id": string; "taskId": string; "identifier": string };
          errors: {
            "NotFound": { "id": string };
            "Unavailable": { "message": string };
          };
          method: "POST";
          path: "/forms/:id/submit";
          gates: ["member"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/forms/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "github": {
        "disconnect": {
          in: unknown;
          out: { "ok": true };
          errors: {};
          method: "DELETE";
          path: "/integrations/github";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "ingest": {
          in: { "title"?: string; "body"?: string; "spaceKey"?: string };
          out: { "id": string; "identifier": string };
          errors: {};
          method: "POST";
          path: "/integrations/github";
          gates: ["member"];
        };
        "status": {
          in: unknown;
          out: { "connected": boolean; "repo"?: string };
          errors: {};
          method: "GET";
          path: "/integrations/github";
          gates: ["member"];
        };
      };
      "goals": {
        "create": {
          in: { "name": string; "status"?: string; "ownerEmail"?: string; "targetDate"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/goals";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/goals/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/goals";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/goals/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "rollup": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/goals/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "inbox": {
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/inbox";
          gates: ["member"];
        };
        "read": {
          in: { "id": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/inbox/:id/read";
          gates: ["member"];
        };
      };
      "main": {
        "health": {
          in: unknown;
          out: { "ok": true };
          errors: {};
          method: "GET";
          path: "/health";
          gates: ["public"];
        };
        "root": {
          in: unknown;
          out: { "ok": true; "app": string; "try": readonly string[]; "console": string };
          errors: {};
          method: "GET";
          path: "/";
          gates: ["public"];
        };
      };
      "members": {
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/members/:id";
          gates: ["member"];
        };
        "invite": {
          in: { "email": string; "role": string; "spaceId"?: string };
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/members/invite";
          gates: ["member","member:admin"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/members";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/members/:id";
          gates: ["member","member:admin"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/members/:id";
          gates: ["member","member:admin"];
        };
      };
      "my": {
        "plan": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "POST";
          path: "/me/plan";
          gates: ["member"];
        };
        "tasksMine": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "GET";
          path: "/me/tasks";
          gates: ["member"];
        };
      };
      "notify": {
        "onComment": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onComplete": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onDraft": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onForm": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onGoal": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onGoalChanged": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onProject": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onTask": {
          in: unknown;
          out: unknown;
          errors: {};
        };
      };
      "overdue": {
        "watch": {
          in: unknown;
          out: unknown;
          errors: {};
        };
      };
      "projects": {
        "addSection": {
          in: { "id": string; "name": string };
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/projects/:id/sections";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "archive": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
          method: "POST";
          path: "/projects/:id/archive";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "create": {
          in: { "spaceId": string; "goalId"?: string; "name": string; "status"?: string; "leadEmail"?: string; "startDate"?: string; "targetDate"?: string; "color"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/projects";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/projects/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/projects";
          gates: ["member"];
        };
        "listSections": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "id": string };
          out: readonly { "id": string; "name": string; "sortOrder": number }[];
          errors: {};
          method: "GET";
          path: "/projects/:id/sections";
          gates: ["member"];
        };
        "listUpdates": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "id": string };
          out: readonly { "id": string; "body": string; "health": string }[];
          errors: {};
          method: "GET";
          path: "/projects/:id/updates";
          gates: ["member"];
        };
        "postUpdate": {
          in: { "body": string; "health"?: string; "id": string };
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/projects/:id/updates";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/projects/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/projects/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "recurring": {
        "spawn": {
          in: unknown;
          out: unknown;
          errors: {};
        };
      };
      "search": {
        "embedTask": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
        };
        "indexOnCreate": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onComment": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onComplete": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onForm": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "onProject": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "query": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly { "id": string; "title": string; "identifier": string }[];
          errors: {};
          method: "QUERY";
          path: "/search";
          gates: ["member"];
        };
        "reindex": {
          in: unknown;
          out: { "ok": true };
          errors: {};
          method: "POST";
          path: "/search/reindex";
          gates: ["member"];
        };
        "suggest": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly { "id": string; "title": string; "identifier": string }[];
          errors: {};
          method: "GET";
          path: "/search/suggest";
          gates: ["member"];
        };
      };
      "slack": {
        "ingest": {
          in: { "text": string; "channel"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/integrations/slack";
          gates: ["member"];
        };
      };
      "spaces": {
        "create": {
          in: { "key": string; "name": string; "color"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/spaces";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/spaces/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/spaces";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/spaces/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/spaces/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "tags": {
        "create": {
          in: { "name": string; "groupName"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/tags";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: { "id": string; "name": string; "groupName": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/tags/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly { "id": string; "name": string; "groupName": string | null }[];
          errors: {};
          method: "GET";
          path: "/tags";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/tags/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/tags/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "tasks": {
        "addTag": {
          in: { "id": string; "tagId": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/tags";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "archive": {
          in: { "id": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/archive";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "assign": {
          in: { "id": string; "assigneeEmail": string };
          out: { "id": string; "identifier": string; "userId": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/assign";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "complete": {
          in: { "id": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/complete";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "create": {
          in: { "title": string; "spaceKey": string; "description"?: string; "priority"?: number; "projectId"?: string; "sectionId"?: string; "parentId"?: string; "dueDate"?: string; "startDate"?: string; "roleNeeded"?: string; "kind"?: string; "assigneeEmail"?: string };
          out: { "id": string; "identifier": string; "userId": string | null };
          errors: {
            "NotFound": { "id": string };
            "Duplicate": { "id"?: string; "identifier"?: string };
          };
          method: "POST";
          path: "/tasks";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "depend": {
          in: { "id": string; "blocksTaskId": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
            "Duplicate": { "id"?: string; "identifier"?: string };
          };
          method: "POST";
          path: "/tasks/:id/depend";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "duplicate": {
          in: { "id": string };
          out: { "id": string; "identifier": string; "userId": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/duplicate";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "follow": {
          in: { "id": string };
          out: { "ok": true };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/follow";
          gates: ["member"];
        };
        "get": {
          in: { "id": string };
          out: { "id": string; "identifier": string; "title": string; "description": string | null; "kind": string; "priority": number; "estimate": number | null; "status": string; "spaceId": string; "projectId": string | null; "sectionId": string | null; "parentId": string | null; "dueDate": string | null; "completedAt": string | null; "archivedAt": string | null; "roleNeeded": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/tasks/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "spaceKey"?: string; "projectId"?: string; "status"?: string };
          out: readonly { "id": string; "identifier": string; "title": string; "description": string | null; "kind": string; "priority": number; "estimate": number | null; "status": string; "spaceId": string; "projectId": string | null; "sectionId": string | null; "parentId": string | null; "dueDate": string | null; "completedAt": string | null; "archivedAt": string | null; "roleNeeded": string | null }[];
          errors: {};
          method: "GET";
          path: "/tasks";
          gates: ["member"];
        };
        "live": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "GET";
          path: "/tasks/live";
          live: "tasks";
          stream: true;
          matchKey: [];
          gates: ["member"];
        };
        "move": {
          in: { "id": string; "projectId"?: string; "sectionId"?: string; "spaceKey"?: string };
          out: { "id": string; "identifier": string; "userId": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "POST";
          path: "/tasks/:id/move";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "onStatus": {
          in: unknown;
          out: unknown;
          errors: {};
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/tasks/:id";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
        "unfollow": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
          method: "POST";
          path: "/tasks/:id/unfollow";
          gates: ["member"];
        };
        "update": {
          in: { "id": string; "title"?: string; "description"?: string; "priority"?: number; "estimate"?: number | null; "status"?: string; "dueDate"?: string | null; "roleNeeded"?: string | null };
          out: { "id": string; "identifier": string; "title": string; "description": string | null; "kind": string; "priority": number; "estimate": number | null; "status": string; "spaceId": string; "projectId": string | null; "sectionId": string | null; "parentId": string | null; "dueDate": string | null; "completedAt": string | null; "archivedAt": string | null; "roleNeeded": string | null };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/tasks/:id";
          gates: ["member","task:write","rate:sliding-window-counter:60/1m"];
        };
      };
      "views": {
        "board": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string; "id": string };
          out: readonly { "sectionId": string; "name": string; "tasks": readonly { "id": string; "title": string; "identifier": string }[] }[];
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/views/:id/board";
          gates: ["member"];
        };
        "create": {
          in: { "projectId": string; "name": string; "kind": "list" | "board" | "timeline" | "calendar"; "filtersJson"?: string; "ownerEmail"?: string };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/views";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "get": {
          in: { "id": string };
          out: {  };
          errors: {
            "NotFound": { "id": string };
          };
          method: "GET";
          path: "/views/:id";
          gates: ["member"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly unknown[];
          errors: {};
          method: "GET";
          path: "/views";
          gates: ["member"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/views/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
        "update": {
          in: unknown;
          out: { "id": string };
          errors: {
            "NotFound": { "id": string };
          };
          method: "PATCH";
          path: "/views/:id";
          gates: ["member","project:admin","rate:token-bucket:40/1m"];
        };
      };
      "webhooks": {
        "create": {
          in: { "url": string; "events"?: readonly string[] };
          out: { "id": string };
          errors: {};
          method: "POST";
          path: "/webhooks";
          gates: ["member","webhook:admin"];
        };
        "list": {
          in: { "q"?: string; "search"?: string; "limit"?: number; "order"?: string; "orderBy"?: string; "select"?: string; "or"?: string; "and"?: string; "offset"?: number; "cursor"?: string };
          out: readonly { "id": string; "url": string }[];
          errors: {};
          method: "GET";
          path: "/webhooks";
          gates: ["member","webhook:admin"];
        };
        "remove": {
          in: unknown;
          out: unknown;
          errors: {};
          method: "DELETE";
          path: "/webhooks/:id";
          gates: ["member","webhook:admin"];
        };
        "rotate": {
          in: { "id": string };
          out: { "ok": true };
          errors: {};
          method: "POST";
          path: "/webhooks/:id/rotate";
          gates: ["member","webhook:admin"];
        };
      }
      };
    };
  }
}

export {};
