// AUTO-GENERATED by `oke dev` / `oke build` — do not edit by hand.
// Regenerated from every `src/flows/<unit>/` folder (barrel or file tree).
import { registerFlowUnits, stampFlowName, stampHttpPath } from "okengine";
import * as links_$code$_archive from "./links/[code]/archive.ts";
import * as links_$code$_get from "./links/[code]/get.ts";
import * as links_$code$_report from "./links/[code]/report.ts";
import * as links_create from "./links/create.ts";
import * as links_expire from "./links/expire.ts";
import * as links_list from "./links/list.ts";
import * as links_reach from "./links/reach.ts";
import * as links_redirect from "./links/redirect.ts";
import * as links_signals from "./links/signals.ts";

const links = {
  archive: stampHttpPath(stampFlowName(links_$code$_archive.archive, "links.archive"), "/links/:code/archive"),
  get: stampHttpPath(stampFlowName(links_$code$_get.get, "links.get"), "/links/:code"),
  report: stampHttpPath(stampFlowName(links_$code$_report.report, "links.report"), "/links/:code/report"),
  create: stampHttpPath(stampFlowName(links_create.create, "links.create"), "/links"),
  expire: stampHttpPath(stampFlowName(links_expire.expire, "links.expire"), "/links/expire"),
  list: stampHttpPath(stampFlowName(links_list.list, "links.list"), "/links"),
  reach: stampHttpPath(stampFlowName(links_reach.reach, "links.reach"), "/links/reach"),
  redirect: stampHttpPath(stampFlowName(links_redirect.redirect, "links.redirect"), "/links/redirect"),
  onCreated: stampHttpPath(stampFlowName(links_signals.onCreated, "links.onCreated"), "/links/on-created"),
  onClicked: stampHttpPath(stampFlowName(links_signals.onClicked, "links.onClicked"), "/links/on-clicked"),
};
export { links };

import * as main_health from "./main/health.ts";
import * as main_route from "./main/route.ts";

const main = {
  health: stampHttpPath(stampFlowName(main_health.health, "main.health"), "/health"),
  root: stampHttpPath(stampFlowName(main_route.root, "main.root"), "/"),
};
export { main };
registerFlowUnits({ links, main });
declare module "okengine" {
  interface RegisteredFlowUnits {
    readonly links: typeof links;
    readonly main: typeof main;
  }
}
