import "./core";
import "./locales/en";
import "./locales/ar";

import { oke } from "okengine";
import * as routes from "./flows/generated";

// stores (store.sql/store.files) · secrets (vault.secret) · signals (signal())
// · channel templates (channel.<medium>().template()) auto-register from
// `./core` (and `./flows/notes/signals`) — no explicit arrays needed.
// `./flows/generated` is a real file, regenerated by `oke dev` / `oke build`
// from every `src/flows/<unit>/index.ts` folder — never edit it by hand.
export const app = oke({ name: "notes" }).adopt(routes);

export type App = typeof app;
