// AUTO-GENERATED by `oke dev` / `oke build` — do not edit by hand.
// Regenerated from every `src/flows/<unit>/` folder (barrel or file tree).
import { registerFlowUnits, stampFlowName, stampHttpPath } from "okengine";
import * as main_health from "./main/health.ts";
import * as main_route from "./main/route.ts";

const main = {
  health: stampHttpPath(stampFlowName(main_health.health, "main.health"), "/health"),
  root: stampHttpPath(stampFlowName(main_route.root, "main.root"), "/"),
};
export { main };

import * as notes_$id$_archive from "./notes/[id]/archive.ts";
import * as notes_$id$_attach from "./notes/[id]/attach.ts";
import * as notes_$id$_get from "./notes/[id]/get.ts";
import * as notes_$id$_summarize from "./notes/[id]/summarize.ts";
import * as notes_create from "./notes/create.ts";
import * as notes_digest from "./notes/digest.ts";
import * as notes_list from "./notes/list.ts";
import * as notes_on_created from "./notes/on-created.ts";

const notes = {
  archive: stampHttpPath(stampFlowName(notes_$id$_archive.archive, "notes.archive"), "/notes/:id/archive"),
  attach: stampHttpPath(stampFlowName(notes_$id$_attach.attach, "notes.attach"), "/notes/:id/attach"),
  get: stampHttpPath(stampFlowName(notes_$id$_get.get, "notes.get"), "/notes/:id"),
  summarize: stampHttpPath(stampFlowName(notes_$id$_summarize.summarize, "notes.summarize"), "/notes/:id/summarize"),
  create: stampHttpPath(stampFlowName(notes_create.create, "notes.create"), "/notes"),
  digest: stampHttpPath(stampFlowName(notes_digest.digest, "notes.digest"), "/notes/digest"),
  list: stampHttpPath(stampFlowName(notes_list.list, "notes.list"), "/notes"),
  onCreated: stampHttpPath(stampFlowName(notes_on_created.onCreated, "notes.onCreated"), "/notes/on-created"),
};
export { notes };
registerFlowUnits({ main, notes });
declare module "okengine" {
  interface RegisteredFlowUnits {
    readonly main: typeof main;
    readonly notes: typeof notes;
  }
}
