// AUTO-GENERATED by `oke dev` / `oke build` — do not edit by hand.
// Regenerated from every `src/flows/<unit>/` folder (barrel or file tree).
import { registerFlowUnits, stampFlowName, stampHttpPath } from "okengine";
import * as main_health from "./main/health.ts";
import * as main_route from "./main/route.ts";

const main = {
  health: stampHttpPath(stampFlowName(main_health.health, "main.health"), "/health"),
  root: stampHttpPath(stampFlowName(main_route.root, "main.root"), "/"),
};
export { main };

registerFlowUnits({ main });
declare module "okengine" {
  interface RegisteredFlowUnits {
    readonly main: typeof main;
  }
}
