// generated by oke — do not edit
import { pgTable, text, bigint } from "drizzle-orm/pg-core";
import { id } from "okengine/store";
import { links } from "./links.ts";

export const daily = pgTable("daily", {
  id: text("id").primaryKey().$defaultFn(id),
  code: text("code").notNull().references(() => links.code, { onDelete: "cascade" }),
  day: text("day").notNull(),
  clicks: bigint("clicks", { mode: "number" }).notNull().default(0),
});
