// generated by oke — do not edit
import { pgTable, text, bigint, timestamp, pgPolicy } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { id, nowDate } from "okengine/store";

export const links = pgTable.withRLS("links", {
  id: text("id").primaryKey().$defaultFn(id),
  userId: text("user_id").notNull(),
  code: text("code").notNull().unique(),
  url: text("url").notNull(),
  clicks: bigint("clicks", { mode: "number" }).notNull().default(0),
  expiresAt: timestamp("expires_at", { mode: "date" }),
  archivedAt: timestamp("archived_at", { mode: "date" }),
  createdAt: timestamp("created_at", { mode: "date" }).notNull().$defaultFn(nowDate),
}, (_t) => [
  pgPolicy("public read", {
    as: "permissive",
    to: "public",
    for: "select",
    using: sql`true`,
  }),
  pgPolicy("gate_member_insert", {
    as: "permissive",
    to: "public",
    for: "insert",
    withCheck: sql`oke.gate() = 'member'`,
  }),
  pgPolicy("owner_userId_insert", {
    as: "permissive",
    to: "public",
    for: "insert",
    withCheck: sql`userId = oke.user()`,
  }),
]);
