// generated by oke — do not edit
import { defineRelations } from "drizzle-orm";
import { daily } from "./daily.ts";
import { links } from "./links.ts";

export const relations = defineRelations({ links, daily }, (r) => ({
  links: {
    daily: r.many.daily({ from: r.links.code, to: r.daily.code }),
  },
  daily: {
    link: r.one.links({ from: r.daily.code, to: r.links.code, optional: false }),
  },
}));
