name: PR meta

on:
  pull_request:
    types:
      [opened, edited, synchronize, labeled, unlabeled, milestoned, demilestoned, ready_for_review]

permissions:
  contents: read
  pull-requests: read
  issues: read

concurrency:
  group: pr-meta-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-meta:
    name: pr-meta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 1
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: "1.4.2"
      - name: Check pull request metadata
        env:
          PROJECT_TOKEN: ${{ secrets.PROJECT_TOKEN }}
        run: bun scripts/github/check-pr.ts
